### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by yuanze-lin** [jayleicn/singularity#10]
Hi, dear authors, how do you pre-process DiDeMo dataset?

**Comment by jayleicn** [comment]
Hi @yzleroy, Please see Section 4.1, where we mentioned 
> For DiDeMo and ActivityNet Captions, we evaluate paragraph-to- video retrieval [43, 31, 47], where the text captions in the same video are concatenated as a single paragraph-level text for retrieval.

**Comment by yzleroy** [comment]
> 

Yes, I've seen this section, but I don't know how do you pre-process the videos of DiDeMo dataset? I see that you firstly compress the video dataset into 224 x 224 spatial size. However, in the ret_didemo.yaml file, the file name is didemo_2fps_360_trimed30, I'm confused.

**Comment by yzleroy** [comment]
> Hi @yzleroy, Please see Section 4.1, where we mentioned
> 
> > For DiDeMo and ActivityNet Captions, we evaluate paragraph-to- video retrieval [43, 31, 47], where the text captions in the same video are concatenated as a single paragraph-level text for retrieval.

Yes, I've seen this section, but I don't know how do you pre-process the videos of DiDeMo dataset? I see that you firstly compress the video dataset into 224 x 224 spatial size. However, in the ret_didemo.yaml file, the file name is didemo_2fps_360_trimed30, I'm confused.

**Comment by jayleicn** [comment]
trimed30 means we keep only the first 30 seconds of the videos, following the setup in the original didemo paper.

**Comment by yuanze-lin** [comment]
> trimed30 means we keep only the first 30 seconds of the videos, following the setup in the original didemo paper.

Thank you for your kind response !
