### ISSUE TITLE
Apply to new dataset

### ISSUE THREAD

**Issue by nikky4D** [jayleicn/singularity#11]
Hi, Can you give me instructions of how to set up for my own custom dataset? I have about 100 folders of images, with each folder containing the images from a video clip. I also have captions for each of these video clips. How would I use this custom dataset for finetuning for text-video retrieval?

**Comment by jayleicn** [comment]
Hi @nikky4D, I have updated the readme to include instructions on custom datasets, please see https://github.com/jayleicn/singularity#pre-training-on-custom-data.

**Comment by nikky4D** [comment]
Thanks. Are these instructions the same for finetuning? My dataset is too small for full pretrain so I want to attempt finetune to see the results.

**Comment by jayleicn** [comment]
Yes.

**Comment by nikky4D** [comment]
Thank you
