### ISSUE TITLE
Is msrvtt_ret_train9k.json used anywhere?

### ISSUE THREAD

**Issue by TheShadow29** [jayleicn/singularity#13]
Hello, thanks for the releasing code. This is really inspiring work. I noticed that in the downstream data, there is `msrvtt_ret_train9k.json` file, but I don't see it being used anywhere. I am guessing it is train+val? 

If I understand correctly, msrvtt_ret_train7k.json is used for training, and msrvtt_ret_test1k.json is used for testing, and nothing is for validation?

**Comment by jayleicn** [comment]
Hi @TheShadow29, 

`msrvtt_ret_train9k.json` is not used. 
> msrvtt_ret_train7k.json is used for training, and msrvtt_ret_test1k.json is used for testing

This is correct.
