### ISSUE TITLE
About "Rerank dual-encoder results with cross-encoder“

### ISSUE THREAD

**Issue by ruiyan1995** [jayleicn/singularity#14]
https://github.com/jayleicn/singularity/blob/ef0cdbbcfa38ed9218565453d95e4dca25e2a5cb/tasks/retrieval_utils.py#L119

Hi, authors. Thanks for your great work. Could you provide any explanation or reference for this 're-ranking' trick? It seems to bring significant improvements on ret task, as shown below.
![117821657473558_ pic](https://user-images.githubusercontent.com/8198101/178155284-baca96f8-e027-4db3-bf89-86a2efc714db.jpg)
.

**Comment by FangmingZhou** [comment]
The dual tower part does ranking first, after that, only the topK highest candidates can be reranked by the single-tower part. You can regard the single tower as a more concise but time-consuming module.
So, it's not a trick, but two module explained in the paper

**Comment by ruiyan1995** [comment]
@FangmingZhou Thanks for your reply very much! Could you point out the explanation in the paper? Sorry, I cannot find it.😢

**Comment by FangmingZhou** [comment]
> @FangmingZhou Thanks for your reply very much! Could you point out the explanation in the paper? Sorry, I cannot find it.😢

The Method part in page 3:  F_l(S)   F_v(f_t) is the dual tower, H(*) is the single tower

**Comment by FangmingZhou** [comment]
You can learn more about this strategy from ALBEL paper
