### ISSUE TITLE
How to run Open-ended QA

### ISSUE THREAD

**Issue by ShuangLI59** [jayleicn/singularity#16]
Can I ask how to run open-ended QA on ActivityNet? (Generate text answer instead of doing classification)

**Comment by jayleicn** [comment]
Hi @ShuangLI59, Please check the instructions in https://github.com/jayleicn/singularity#question-answering.

**Comment by ShuangLI59** [comment]
Sorry, I couldn't find it. Given a video and a question, how to generate an open-language answer? Could you provide the command?

**Comment by ShuangLI59** [comment]
Thanks for your reply. Sorry, I couldn't find the code for generating open-language answers. The link you provided is for selecting answers from predefined classes. Given a video and a question, how to generate an open-language answer? Could you provide the command? Thanks.

**Comment by jayleicn** [comment]
Yes, we perform open-ended QA in a somewhat closed setup, by selecting only among the top-N most frequent answers. That is how [training](https://github.com/jayleicn/singularity#question-answering) and [evaluation](https://github.com/jayleicn/singularity#evaluation) (last paragraph) work. 

To lose this closed constraint, you may need to modify the inference code [here](https://github.com/jayleicn/singularity/blob/ef0cdbbcfa38ed9218565453d95e4dca25e2a5cb/models/model_vqa.py#L87), especially you need to change this function [rank_answer.py](https://github.com/jayleicn/singularity/blob/ef0cdbbcfa38ed9218565453d95e4dca25e2a5cb/models/model_vqa.py#L101). You are welcome to make a PR on it.

**Comment by ShuangLI59** [comment]
Thanks for your reply. I have one question about the rank_answer function. Can I ask why answer_ids is provided during inference? Do you mind providing the code of experiments in Appendix A.1 / Figure 8a (Open-ended QA model)?
