### ISSUE TITLE
Data/model server offline

### ISSUE THREAD

**Issue by YiLi-Intel** [jayleicn/singularity#20]
Hello,

Thanks for open sourcing the code for this cool work! It seems that the server hosting data annotations and model checkpoints (under vision.cs.unc.edu domain) has gone offline. I wonder if there is an ETA for fixing the network issues?

**Comment by jayleicn** [comment]
Thanks for your appreciation to our work! Our server is down due to a hardware failure, we are working on a fix but we don't have ETA for now. We'll keep you posted.

**Comment by YiLi-Intel** [comment]
Thank you for the prompt response! Take your time and hope the server will be back online soon.

**Comment by andrewhinh** [comment]
Hey, having this same issue. Any update on a fix for this?

**Comment by tmliang** [comment]
Still waiting 😭

**Comment by Andy1621** [comment]
Could you please provide the backup on Google Drive? Thanks!

**Comment by kylemin** [comment]
It's been over a month. Could you upload the weights to Google Drive? @jayleicn

**Comment by jayleicn** [comment]
Hi All, 

We have brought back the data in a1d3ac60f58553acf1ec9ca28f4ef6643036f5ad, please check the updated links in README. Sorry for this inconvenience. 

Best,
Jie

**Comment by tmliang** [comment]
> Hi All,
> 
> We have brought back the data in [a1d3ac6](https://github.com/jayleicn/singularity/commit/a1d3ac60f58553acf1ec9ca28f4ef6643036f5ad), please check the updated links in README. Sorry for this inconvenience.
> 
> Best, Jie

Hi Jay, the new links seem to be closed again

**Comment by kylemin** [comment]
> > Hi All,
> > We have brought back the data in [a1d3ac6](https://github.com/jayleicn/singularity/commit/a1d3ac60f58553acf1ec9ca28f4ef6643036f5ad), please check the updated links in README. Sorry for this inconvenience.
> > Best, Jie
> 
> Hi Jay, the new links seem to be closed again

@jayleicn Now they're not working again
