### ISSUE TITLE
A question about whether to try other data sets.

### ISSUE THREAD

**Issue by Decem-Y** [jayleicn/singularity#3]
Have you tried to verify the effect of the model on SNLI-VE dataset?

**Comment by jayleicn** [comment]
Hi @Decem-Y, we don’t have plans for it, esp because we focus on video-text tasks.

**Comment by Decem-Y** [comment]
> Hi @Decem-Y, we don’t have plans for it, esp because we focus on video-text tasks.

OK, thanks for your reply, but SNLI-VE is a fine-grained visual reasoning task to predict whether
the relationship between an image and a text is entailment, neutral, or contradictory. Maybe its test data has been reported to be noisy.
