### ISSUE TITLE
typos in preprint paper

### ISSUE THREAD

**Issue by FangmingZhou** [jayleicn/singularity#4]
No offense, just want to mention some typos in the Introduction part of the preprint paper:

-  the **find-grained** action recognition dataset Something-Something v2 (SSv2) 
-  (ii) We propose two new tasks specifically designed for testing models’ ability for **find-grained** temporal modeling.

By the way, this is a wonderful paper with smart insight!

**Comment by jayleicn** [comment]
Thanks for your appreciation of our work!  And thanks for spotting these typos, we'll fix them in revision.
