### ISSUE TITLE
Training Error  

### ISSUE THREAD

**Issue by yuanze-lin** [jayleicn/singularity#7]
I have tried to training the models, however, after about 1 epoch, the error will appear, I use 8 A5000 for training.

**Comment by yzleroy** [comment]
<img width="1637" alt="WeChat630baf015129f2b66846860af4369bd1" src="https://user-images.githubusercontent.com/24366920/174729899-f7e301f3-edc0-4336-a000-69923b5499ec.png">

**Comment by jayleicn** [comment]
Hi @yzleroy, this does not seem like a bug from our code but instead from pytorch distributed. Could you try to resume the training and see if this is a persistent issue?

**Comment by yuanze-lin** [comment]
> Hi @yzleroy, this does not seem like a bug from our code but instead from pytorch distributed. Could you try to resume the training and see if this is a persistent issue?

I try to train the models from scratch multiple times, this error always appears, so I don't know how to solve this problem.

**Comment by jayleicn** [comment]
Can you try single-GPU training to see what happens?

**Comment by jayleicn** [comment]
Hi @yzleroy, could you write a bit about how you solved the issue? This is helpful for future readers. Thanks

**Comment by yuanze-lin** [comment]
> Hi @yzleroy, could you write a bit about how you solved the issue? This is helpful for future readers. Thanks

I found it was caused by the hardware devices : )
