### ISSUE TITLE
Zero-shot performance on SSv2

### ISSUE THREAD

**Issue by vateye** [jayleicn/singularity#8]
Hi, I am curious about the zero-shot performance of different model on SSv2. Did you have the zero-shot performance of singularity on SSv2 label and template? Thanks.

**Comment by jayleicn** [comment]
Hi @vateye, we don't have results on SSv2 zero-shot, but it should be easy to evaluate it yourself using our code, following the instructions here: https://github.com/jayleicn/singularity#evaluation.
